

GET http://localhost:3000/api/users

###

POST https://shiny-palm-tree-94j47gq9v4pcxwvx-3000.app.github.dev/api/suggestions
content-type: application/json

{
    "genres": ["Acción", "Aventura", "Comedia", "Superheroes"],
    "likes": ["Stranger Things", "El señor de los anillos", "Spiderman"],
    "dislikes": ["Hulk", "La La Land", "Hamilton"]
}

###

POST https://shiny-palm-tree-94j47gq9v4pcxwvx-3000.app.github.dev/api/groups
content-type: application/json
{
  "name": "Los pibes",
  "minAge": 15,
  "maxAge": 18,
  "likes": [],
  "dislikes": [],
  "users": []
}

###