
@host = {{$processEnv [%]HOST}}
@port = {{$processEnv [%]PORT}}


GET http://localhost:3000/api/users

###

POST https://shiny-palm-tree-94j47gq9v4pcxwvx-3000.app.github.dev/api/suggestions
content-type: application/json

{
    "genres": ["Acción", "Aventura", "Comedia", "Superheroes"],
    "likes": ["Stranger Things", "El señor de los anillos", "Spiderman"],
    "dislikes": ["Hulk", "La La Land", "Hamilton"]
}

###

POST http://localhost:3000/api/groups
content-type: application/json

{
  "name": "Grupo de amigos",
  "minAge": {{$randomInt 10 15}},
  "maxAge": {{$randomInt 20 30}},
  "likes": [],
  "dislikes": [],
  "users": ["66c7e700d675415dfd7ce87f", "66c884c54c0d99e1efe8e1e3", "66cce65e68119672c178f8e1"]
}

###