export const catalogue = [
    "500 Days of Summer",
    "Deadpool",
    "Mi villano favorito",
    "Alien",
    "Blade Runner 2049",
    "Bohemian Rhapsody",
    "Dark",
    "Dead Poets Society",
    "Donnie Darko",
    "El Conjuro",
    "El Padrino",
    "Eternal Sunshine of the Spotless Mind",
    "Fight Club",
    "Forrest Gump",
    "Juno",
    "Las ventajas de ser invisible",
    "Matrix",
    "Interestelar",
    "Zodiac",
    "Oppenheimer",

    "Atypical",
    "Breaking Bad",
    "Dark",
    "Black Mirror",
    "Dr. House",
    "Friends",
    "Game of Thrones",
    "Grey's Anatomy",
    "La Casa de Papel",
    "Merlina",
    "Merlí",
    "Modern Family",
    "Mr. Robot",
    "Narcos",
    "Peaky Blinders",
    "Rick and Morty",
    "Sherlock",
    "Stranger Things",
    "The Big Bang Theory",
    "The Office",
]