export const mediaPaths = {
   
    "500 Days of Summer": "src\\assets\\images\\500-days-of-summer.jpg",
    "A Ghost Story": "src\\assets\\images\\a-ghost-story.jpeg",
    "A Scanner Darkly": "src\\assets\\images\\a-scanner-darkly.jpg",
    "Akira": "src\\assets\\images\\akira.jpg",
    "Alien": "src\\assets\\images\\alien.webp",
    "American Horror Story": "src\\assets\\images\\american-horror-stories.webp",
    "Annihilation": "src\\assets\\images\\annihilation.jpg",
    "Archer": "src\\assets\\images\\archer.jpg",
    "Arrested Development": "src\\assets\\images\\arrested-development.jpg",
    "Arrival": "src\\assets\\images\\arrival.jpg",
    "Atypical": "src\\assets\\images\\atypical.jpg",
    "Black Mirror": "src\\assets\\images\\black-mirror.jpg",
    "Blade Runner 2049": "src\\assets\\images\\blade-runner-2049.webp",
    "Bohemian Rhapsody": "src\\assets\\images\\bohemian-rhapsody.jpg",
    "BoJack Horseman": "src\\assets\\images\\bojack-horseman.jpg",
    "Breaking Bad": "src\\assets\\images\\breaking-bad.jpg",
    "Bridgerton": "src\\assets\\images\\bridgerton.jpg",
    "Brooklyn Nine-Nine": "src\\assets\\images\\brooklyn-nine-nine.jpg",
    "Cobra Kai": "src\\assets\\images\\cobra-kai.jpg", 
    "Community": "src\\assets\\images\\community.jpg",  
    "Daredevil": "src\\assets\\images\\daredevil.jpg",  
    "Dark": "src\\assets\\images\\dark.jpg",
    "Dead Poets Society": "src\\assets\\images\\dead-poets-society.jpg",
    "Doctor Who": "src\\assets\\images\\doctor-who.jpg",
    "Donnie Darko": "src\\assets\\images\\donnie-darko.jpg",
    "Dr House": "src\\assets\\images\\dr-house.jpeg",
    "Edge of Tomorrow": "src\\assets\\images\\edge-of-tomorrow.jpg",
    "El Conjuro": "src\\assets\\images\\el-conjuro.jpeg",
    "El Padrino": "src\\assets\\images\\el-padrino.webp",
    "El Reino": "src\\assets\\images\\el-reino.jpg",
    "El Zodiaco": "src\\assets\\images\\zodiac.jpg",
    "Eternal Sunshine of the Spotless Mind": "src\\assets\\images\\eternal-sunshine-of-the-spotless-mind.jpeg",
    "Euphoria": "src\\assets\\images\\euphoria.jpg",
    "Forrest Gump": "src\\assets\\images\\forrest-gump.jpg",
    "Friends": "src\\assets\\images\\friends.jpg",
    "Futurama": "src\\assets\\images\\futurama.jpg",
    "Game of Thrones": "src\\assets\\images\\game-of-thrones.jpg",
    "Glee": "src\\assets\\images\\glee.jpg",
    "Greys Anatomy": "src\\assets\\images\\greys-anatomy.jpg",
    "Guardians of the Galaxy": "src\\assets\\images\\guardians-of-the-galaxy.jpg",
    "Hereditary": "src\\assets\\images\\hereditary .jpg",
    "Howl's Moving Castle": "src\\assets\\images\\howls-moving-castle.jpg",
    "House Of Cards": "src\\assets\\images\\house-of-cards.jpg",
    "Interestelar": "src\\assets\\images\\interestelar.jpg",
    "John Wick: Capitulo 4": "src\\assets\\images\\john-wick-capitulo4.webp",
    "John Wick": "src\\assets\\images\\john-wick.jpg",
    "Juno": "src\\assets\\images\\juno.jpg",
    "La La Land": "src\\assets\\la-la-land.jpg",
    "Las Ventajas de Ser Invisible": "src\\assets\\images\\las-ventajas-de-ser-invisible.jpg",
    "Locke & Key": "src\\assets\\images\\locke-&-key.jpg",
    "Los Simuladores": "src\\assets\\images\\los-simuladores.jpg",
    "Love, Death & Robots": "src\\assets\\images\\love-death-robots.jpg",
    "Mad Max: Fury Road": "src\\assets\\images\\mad-max-fury-road.jpg",
    "Mamma Mia": "src\\assets\\images\\mamma-mia.webp",
    "Merlina": "src\\assets\\images\\merlina.jpg",
    "Mindhunter": "src\\assets\\images\\mindhunter.webp",
    "Mr Robot": "src\\assets\\images\\mr-robot.jpg",
    "Narcos": "src\\assets\\images\\narcos.jpg",
    "Nueve Reinas": "src\\assets\\images\\nueve-reinas.jpg",
    "Okupas": "src\\assets\\images\\okupas.jpg",
    "Oppenheimer": "src\\assets\\images\\oppenheimer.jpg",
    "Orgullo y prejuicio": "src\\assets\\images\\orgullo-y-prejuicio.jpg",
    "Paprika": "src\\assets\\images\\paprika.jpg",
    "Parks and Recreation": "src\\assets\\images\\parks-and-recreation.jpg",
    "Peaky Blinders": "src\\assets\\images\\peaky-blinders.jpg",
    "Rick and Morty": "src\\assets\\images\\rick-y-morty.jpg",
    "Scott Pilgrim vs. the World": "src\\assets\\images\\scott-pilgrim-vs-the-world.jpg",
    "Sense8": "src\\assets\\images\\sense-8.jpg",
    "Sex Education": "src\\assets\\images\\sex-education.jpg",
    "Shaun of the Dead": "src\\assets\\images\\shaun-of-the-dead.jpg",
    "Sherlock": "src\\assets\\images\\sherlock.jpg", 
    "Shrek": "src\\assets\\images\\shrek.jpg",
    "Sinister": "src\\assets\\images\\sinister.jpg",
    "Spider-Man: Into the Spider-Verse": "src\\assets\\images\\spiderman-into-the-spiderverse.jpg",
    "Spirited Away": "src\\assets\\images\\spirited-away.jpg",
    "Stranger Things": "src\\assets\\images\\stranger-things.jpg",
    "Ted Lasso": "src\\assets\\images\\ted-lasso.jpg",
    "The Babadook": "src\\assets\\images\\the-babadook.jpg",
    "The Batman": "src\\assets\\images\\the-batman.jpg",
    "The Boys": "src\\assets\\images\\the-boys.jpg",
    "The Cabin in the Woods": "src\\assets\\images\\the-cabin-in-the-woods.jpg",
    "The Conjuring": "src\\assets\\images\\the-conjuring.jpeg",
    "The Crown": "src\\assets\\images\\the-crown.jpg",
    "The Expanse": "src\\assets\\images\\the-expanse.jpg",
    "The Good Doctor": "src\\assets\\images\\the-good-doctor.jpg",
    "The Good Place": "src\\assets\\images\\the-good-place.jpg",
    "The Handmaid's Tale": "src\\assets\\images\\the-handmaids-tale.jpg",
    "The Haunting of Hill House": "src\\assets\\images\\the-haunting-of-hill-house.jpg",
    "The IT Crowd": "src\\assets\\images\\the-it-crowd.jpg",
    "The Lighthouse": "src\\assets\\images\\the-lighthouse.jpg",
    "The Lord of the Rings: The Fellowship of the Ring": "src\\assets\\images\\the-lord-of-the-rings-the-fellowship-of-the-ring .jpg",
    "The Mandalorian": "src\\assets\\images\\the-madalorian.webp",
    "The Martian": "src\\assets\\images\\the-martian.jpg",
    "The Matrix": "src\\assets\\images\\the-matrix.jpg",
    "The Mitchells vs. the Machines": "src\\assets\\images\\the-mitchells-vs-the-machines.jpg",
    "The Nice Guys": "src\\assets\\images\\the-nice-guy.jpg",
    "The OA": "src\\assets\\images\\the-oa.webp",
    "The Office (US)": "src\\assets\\images\\the-office.jpg",
    "The Orville": "src\\assets\\images\\the-orville.jpg",
    "The Raid: Redemption": "src\\assets\\images\\the-raid-redemption.jpg",
    "The Rain": "src\\assets\\images\\the-rain.jpeg",
    "The Secret World of Arrietty": "src\\assets\\images\\the-secret-world-of-arriety.jpg",
    "The Twilight Zone": "src\\assets\\images\\the-twilight-zone.jpg",
    "The Umbrella Academy": "src\\assets\\images\\the-umbrella-academy.jpg",
    "The Walking Dead": "src\\assets\\images\\the-walking-dead.jpg",
    "The Witch": "src\\assets\\images\\the-witch.jpg",
    "The Witcher": "src\\assets\\images\\the-witcher.jpg",
    "This Is Us": "src\\assets\\images\\this-is-us.jpg",
    "Top Gun": "src\\assets\\images\\top-gun.jpg",
    "Westworld": "src\\assets\\images\\westworld.webp",
    "Your Name.": "src\\assets\\images\\your-name.jpg",
    "Zombieland": "src\\assets\\images\\zombieland.jpg",
}