export const list = [
    {name: "Atypical", path: "src\\assets\\series\\atypical.jpg"},
    {name: "Breaking Bad", path: "src\\assets\\series\\breaking-bad.jpg"},    
    {name: "Dr House", path: "src\\assets\\series\\dr-house.jpeg"},
    {name: "El Reino", path: "src\\assets\\series\\el-reino.jpg"},
    {name: "Friends", path: "src\\assets\\series\\friends.jpg"},
    {name: "Greys Anatomy", path: "src\\assets\\series\\greys-anatomy.jpg"},
    {name: "House Of Cards", path: "src\\assets\\series\\house-of-cards.jpg"},
    {name: "Los Simuladores", path: "src\\assets\\series\\los-simuladores.jpg"},
    {name: "Merlina", path: "src\\assets\\series\\merlina.jpg"},
    {name: "Mr Robot", path: "src\\assets\\series\\mr-robot.jpg"},
    {name: "Okupas", path: "src\\assets\\series\\okupas.jpg"},
    {name: "Sex Education", path: "src\\assets\\series\\sex-education.jpg"},
    {name: "Sherlock", path: "src\\assets\\series\\sherlock.jpg"}, 
    {name: "Stranger Things", path: "src\\assets\\series\\stranger-things.jpg"},
    {name: "The Rain", path: "src\\assets\\series\\the-rain.jpeg"},
    
    {name: "500 Days of Summer", path: "src\\assets\\movies\\500-days-of-summer.jpg"},
    {name: "Alien", path: "src\\assets\\movies\\alien.webp"},
    {name: "Blade Runner 2049", path: "src\\assets\\movies\\blade-runner-2049.webp"},
    {name: "Bohemian Rhapsody", path: "src\\assets\\movies\\bohemian-rhapsody.jpg"},
    {name: "Dark", path: "src\\assets\\movies\\dark.jpg"},
    {name: "Dead Poets Society", path: "src\\assets\\movies\\dead-poets-society.jpg"},
    {name: "Donnie Darko", path: "src\\assets\\movies\\donnie-darko.jpg"},
    {name: "El Conjuro", path: "src\\assets\\movies\\el-conjuro.jpeg"},
    {name: "El Padrino", path: "src\\assets\\movies\\el-padrino.webp"},
    {name: "Eternal Sunshine of the Spotless Mind", path: "src\\assets\\movies\\eternal-sunshine-of-the-spotless-mind.jpeg"},
    {name: "Forrest Gump", path: "src\\assets\\movies\\forrest-gump.jpg"},
    {name: "John Wick", path: "src\\assets\\movies\\john-wick.jpg"},
    {name: "Juno", path: "src\\assets\\movies\\juno.jpg"},
    {name: "Las Ventajas de Ser Invisible", path: "src\\assets\\movies\\las-ventajas-de-ser-invisible.jpg"},
    {name: "Nueve Reinas", path: "src\\assets\\movies\\nueve-reinas.jpg"},
    {name: "Oppenheimer", path: "src\\assets\\movies\\oppenheimer.jpg"},
    {name: "Orgullo y prejuicio", path: "src\\assets\\movies\\orgullo-y-prejuicio.jpg"},
    {name: "El Zodiac", path: "src\\assets\\movies\\zodiac.jpg"},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    {name: "", path: ""},
    ]