export const mediaPaths = {
   
    "500 Days of Summer": "src\\assets\\movies\\500-days-of-summer.jpg",
    "A Ghost Story": "src\\assets\\movies\\a-ghost-story.jpg",
    "A Scanner Darkly": "src\\assets\\movies\\a-scanner-darkly.jpg",
    "Akira": "src\\assets\\movies\\akira.jpg",
    "Alien": "src\\assets\\movies\\alien.webp",
    "Annihilation": "src\\assets\\movies\\annihilation.jpg",
    "Arrival": "src\\assets\\movies\\arrival.jpg",
    "Blade Runner 2049": "src\\assets\\movies\\blade-runner-2049.webp",
    "Bohemian Rhapsody": "src\\assets\\movies\\bohemian-rhapsody.jpg",
    "Dark": "src\\assets\\series\\dark.jpg",
    "Dead Poets Society": "src\\assets\\movies\\dead-poets-society.jpg",
    "Donnie Darko": "src\\assets\\movies\\donnie-darko.jpg",
    "El Conjuro": "src\\assets\\movies\\el-conjuro.jpeg",
    "El Padrino": "src\\assets\\movies\\el-padrino.webp",
    "Eternal Sunshine of the Spotless Mind": "src\\assets\\movies\\eternal-sunshine-of-the-spotless-mind.jpeg",
    "Forrest Gump": "src\\assets\\movies\\forrest-gump.jpg",
    "Hereditary": "src\\assets\\movies\\hereditary.jpg",
    "Interestelar": "src\\assets\\movies\\interestelar.jpg",
    "John Wick": "src\\assets\\movies\\john-wick.jpg",
    "Juno": "src\\assets\\movies\\juno.jpg",
    "La La Land": "src\\assets\\la-la-land.jpg",
    "Las Ventajas de Ser Invisible": "src\\assets\\movies\\las-ventajas-de-ser-invisible.jpg",
    "Nueve Reinas": "src\\assets\\movies\\nueve-reinas.jpg",
    "Oppenheimer": "src\\assets\\movies\\oppenheimer.jpg",
    "Orgullo y prejuicio": "src\\assets\\movies\\orgullo-y-prejuicio.jpg",
    "Paprika": "src\\assets\\movies\\paprika.jpg",
    "Sinister": "src\\assets\\movies\\sinister.jpg",
    "Spirited Away": "src\\assets\\movies\\spirited-away.jpg",
    "The Babadook": "src\\assets\\movies\\the-babadook.jpg",
    "The Batman": "src\\assets\\movies\\the-batman.jpg",
    "The Conjuring": "src\\assets\\movies\\the-conjuring.jpeg",
    "The Lighthouse": "src\\assets\\movies\\the-lighthouse.jpg",
    "The Lord of The Rings:The Fellowship of The Ring":"src\\assets\\movies\\the-lord-of-the-rings-the-fellowship-of-the-ring.jpg",
    "The Matrix": "src\\assets\\movies\\the-matrix.jpg",
    "The Mithcells vs.the Machines": "src\\assets\\movies\\the-mitchells-vs-the-machines.jpg",
    "The Nice Guys": "src\\assets\\movies\\the-nice-guy.jpg",
    "The Secret World of Arrietty": "src\\assets\\movies\\the-secret-world-of-arriety.jpg",
    "The Witch": "src\\assets\\movies\\the-witch.jpg",
    "Your Name.": "src\\assets\\movies\your-name.jpg",
    "El Zodiaco": "src\\assets\\movies\\zodiac.jpg",
    
    
    "American Horror Story": "src\\assets\\series\\american-horror-stories.webp",
    "Arrested Development": "src\\assets\\series\\arrested-development.jpg",
    "Atypical": "src\\assets\\series\\atypical.jpg",
    "Black Mirror": "src\\assets\\series\\black-mirror.jpg",
    "Breaking Bad": "src\\assets\\series\\breaking-bad.jpg",
    "Brooklyn Nine-Nine": "src\\assets\\series\\brooklyn-nine-nine.jpg",
    "Cobra Kai": "src\\assets\\series\\cobra-kai.jpg", 
    "Community": "src\\assets\\series\\community.jpg",  
    "Daredevil": "src\\assets\\series\\daredevil.jpg",  
    "Doctor Who": "src\\assets\\series\\doctor-who.jpg",
    "Dr House": "src\\assets\\series\\dr-house.jpeg",
    "El Reino": "src\\assets\\series\\el-reino.jpg",
    "Euphoria": "src\\assets\\series\\euphoria.jpg",
    "Friends": "src\\assets\\series\\friends.jpg",
    "Game of Thrones": "src\\assets\\series\\game-of-thrones.jpg",
    "Greys Anatomy": "src\\assets\\series\\greys-anatomy.jpg",
    "House Of Cards": "src\\assets\\series\\house-of-cards.jpg",
    "Locke & Key": "src\\assets\\series\\locke-&-key.jpg",
    "Love, Death & Robots": "src\\assets\\series\\love-death-robots.jpg",
    "Los Simuladores": "src\\assets\\series\\los-simuladores.jpg",
    "Merlina": "src\\assets\\series\\merlina.jpg",
    "Mindhunter": "src\\assets\\series\\mindhunter.webp",
    "Mr Robot": "src\\assets\\series\\mr-robot.jpg",
    "Narcos": "src\\assets\\series\\narcos.jpg",
    "Okupas": "src\\assets\\series\\okupas.jpg",
    "Parks and Recreation": "src\\assets\\series\\parks-and-recreation.jpg",
    "Peaky Blinders": "src\\assets\\series\\peaky-blinders.jpg",
    "Rick and Morty": "src\\assets\\series\\rick-y-morty.jpg",
    "Sense8": "src\\assets\\series\\sense-8.jpg",
    "Sex Education": "src\\assets\\series\\sex-education.jpg",
    "Sherlock": "src\\assets\\series\\sherlock.jpg", 
    "Stranger Things": "src\\assets\\series\\stranger-things.jpg",
    "Ted Lasso": "src\\assets\\series\\ted-lasso.jpg",
    "The Rain": "src\\assets\\series\\the rain.jpeg",
    "The Boys": "src\\assets\\series\\the-boys.jpg",
    "The Expanse": "src\\assets\\series\\the-expanse.jpg",
    "The Good Doctor": "src\\assets\\series\\the-good-doctor.jpg",
    "The Good Place": "src\\assets\\series\\the-good-place.jpg",
    "The Haunting of Hill House": "src\\assets\\series\\the-haunting-of-hill-house.jpg",
    "The IT Crowd": "src\\assets\\series\\the-it-crowd.jpg",
    "The Mandalorian": "src\\assets\\series\\the-madalorian.webp",
    "The OA": "src\\assets\\series\\the-oa.webp",
    "The Office (US)": "src\\assets\\series\\the-office.jpg",
    "The Raid: Redemption": "src\\assets\\series\\the-raid-redemption.jpg",
    "The Twilight Zone": "src\\assets\\series\\the-twilight-zone.jpg",
    "The Umbrella Academy": "src\\assets\\series\\the-umbrella-academy.jpg",
    "The Walking Dead": "src\\assets\\series\\the-walking-dead.jpg",
    "The Witcher": "src\\assets\\series\\the-witcher.jpg",
    "This Is Us": "src\\assets\\series\\this-is-us.jpg",
    "Westworld": "src\\assets\\series\\westworld.webp",
}